import type { Metadata } from "next";
import { Separator } from "@/components/ui/separator"

import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
      <div className="w-full max-w-7xl mx-auto min-h-screen flex flex-col">
          <div className="flex-none">
            <Header />
            <Separator />
          </div>

          <main className="flex-1 flex items-center justify-center">
            {children}
          </main>
          
          <div className="flex-none">
            <Separator />
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
